In [1]:
import numpy as np
import pandas as pd
import re
import tensorflow as tf

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rahul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
# printing english stopwords
stopwods=stopwords.words('english')
print(stopwods)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [4]:
# loading the csv file utf-8 encoding
df=pd.read_csv('twitterdata.csv',encoding='ISO-8859-1')

In [5]:
df.head()

0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY _TheSpecialOne_  \
0  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   scotthamilton   
1  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY        mattycus   
2  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY         ElleCTF   
3  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          Karoli   
4  0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY        joy_wolf   

  @switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D  
0  is upset that he can't update his Facebook by ...                                                                   
1  @Kenichan I dived many times for the ball. Man...                                                                   
2    my whole body feels itchy and like its on fire                                                                    
3  @nationwideclass no, it's not behaving at all....                                                                   
4                      @Kwesidei not the whole crew

In [6]:
# checking rows and column
df.shape

(1599999, 6)

In [7]:
# nameing the colime and reading the dataset again
column_names=['target','id','date','flag','user','text']
df=pd.read_csv('twitterdata.csv',names=column_names,encoding='ISO-8859-1')

In [8]:
df.head()

target          id                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                               text  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire   
4           Karoli  @nationwideclass no, it's not behaving at all....

In [9]:
#finding the no of missing values
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [10]:
# checking the distributation of target column

df['target'].value_counts()
    

target
0    800000
4    800000
Name: count, dtype: int64

In [11]:
# convert the target 4 to 1
df.replace({'target':{4:1}},inplace=True)

In [12]:
df['target'].value_counts()


target
0    800000
1    800000
Name: count, dtype: int64

## 0--> negative
## 1--> positive

# Stemming
It is the process of reducing a word to its Root word
exacmple: actor,actress,acting=act

In [13]:
port_stem=PorterStemmer()

In [14]:
def stemming(content):
    stemmed_content=re.sub('[^a-zA-Z]',' ',content)
    stemmed_content=stemmed_content.lower()
    stemmed_content=stemmed_content.split()
    stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content=' '.join(stemmed_content)
    # print(stemmed_content)
    return stemmed_content

In [ ]:
this is not the code

In [ ]:
df['text'] = df['text'].astype(str)


In [ ]:
print(df.dtypes)



In [ ]:


df['stemmed_content']=df['text'].apply(stemming)


In [ ]:
print("sidd")

In [31]:
df=pd.read_csv('stemmedtwitterdataset.csv',encoding='ISO-8859-1')

In [32]:
df.head()

target          id                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                               text  \
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...   
1    scotthamilton  is upset that he can't update his Facebook by ...   
2         mattycus  @Kenichan I dived many times for the ball. Man...   
3          ElleCTF    my whole body feels itchy and like its on fire    
4           Karoli  @nationwideclass no, it's not behaving at all....   

                                     stemmed_content  
0  switchfoot http twitpic com zl awww bummer sho...  
1  upset updat facebook text might cri result sch...  
2  kenichan dive mani time ball manag save rest g...  
3                    whole bodi feel itchi like fire  
4                      nationwideclass behav mad see

In [46]:
df.isnull().sum()

target             0
id                 0
date               0
flag               0
user               0
text               0
stemmed_content    0
dtype: int64

In [79]:
# seperation the data and labels
X=df['stemmed_content'].values
Y=df['target'].values

In [80]:
X


array(['switchfoot http twitpic com zl awww bummer shoulda got david carr third day',
       'upset updat facebook text might cri result school today also blah',
       'kenichan dive mani time ball manag save rest go bound', ...,
       'readi mojo makeov ask detail',
       'happi th birthday boo alll time tupac amaru shakur',
       'happi charitytuesday thenspcc sparkschar speakinguph h'],
      dtype=object)

In [81]:
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [82]:
# spliting the data training and test dataX
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [83]:
X_train

array(['retrorewind great show today', 'still wide awak good',
       'raphi hai dear', ...,
       'buildabear yeah tri yet kinda came oven n thank love seri much',
       'feel well today im sick hate flu even breath well urgghh',
       'read http bit ly ckw cool know guy chat'], dtype=object)

In [84]:
X_test

array(['wow rain day sick', 'watch pineappl express', 'josh shep mate',
       ..., 'love day back work tomorrw thou',
       'papercak might throw traffic',
       'adzyuk might nce cheap addit em look like major airtim'],
      dtype=object)

In [85]:
Y_train

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [86]:
Y_test

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [87]:
df.isnull().sum()

target             0
id                 0
date               0
flag               0
user               0
text               0
stemmed_content    0
dtype: int64

In [88]:
df.dropna(inplace=True)


In [89]:
df.isnull().sum()

target             0
id                 0
date               0
flag               0
user               0
text               0
stemmed_content    0
dtype: int64

In [90]:
# converting the textaldata to numerical data
vectorizer=TfidfVectorizer()
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [91]:
print(X_train)

  (0, 410810)	0.3218403736026031
  (0, 365681)	0.41460113464293163
  (0, 152969)	0.3776275607531222
  (0, 338364)	0.7628381862700486
  (1, 150491)	0.3105192204255133
  (1, 28692)	0.5483731943180142
  (1, 441346)	0.6830798699695361
  (1, 384003)	0.3691429868522367
  (2, 95030)	0.37574811040167677
  (2, 157423)	0.5219552654647517
  (2, 332366)	0.7657519561732702
  (3, 143888)	0.3146866968657337
  (3, 170856)	0.16812262000788783
  (3, 13721)	0.2401642375246812
  (3, 301319)	0.17828517423734444
  (3, 295762)	0.29911337364690993
  (3, 67987)	0.24270801629409655
  (3, 285969)	0.188883972260186
  (3, 226721)	0.3566587252607362
  (3, 120080)	0.293733848490576
  (3, 445011)	0.2711595990651876
  (3, 135944)	0.4063031361036051
  (3, 80636)	0.3835292297173858
  (4, 153758)	0.33091602628455913
  (4, 131954)	0.21668210129177107
  :	:
  (1279601, 217405)	0.2861389702815746
  (1279601, 399979)	0.18705290092713425
  (1279601, 415585)	0.21923016276380375
  (1279601, 453042)	0.229228460188254
  (1279601,

In [92]:
print(X_test)

  (0, 445699)	0.5626300524119298
  (0, 366583)	0.529007160232232
  (0, 331177)	0.5285068720861448
  (0, 93609)	0.35253274273987417
  (1, 436124)	0.3316661671124705
  (1, 315957)	0.6943652281259849
  (1, 125925)	0.6386348593386298
  (2, 363448)	0.7160256461818862
  (2, 254333)	0.46360317780255983
  (2, 202339)	0.5218997677152007
  (3, 407500)	0.23616121648171529
  (3, 386695)	0.3824810184866783
  (3, 354584)	0.3325808954828312
  (3, 322467)	0.31169944506506464
  (3, 315052)	0.4746997405440727
  (3, 261781)	0.3112271791072081
  (3, 240023)	0.16385714815543026
  (3, 234133)	0.13852179207400306
  (3, 150112)	0.31563953896135527
  (3, 132059)	0.19573372235668549
  (3, 124327)	0.22368189134744526
  (3, 81931)	0.18427236505907085
  (4, 359311)	0.38718341121573974
  (4, 318416)	0.3687461189844583
  (4, 285969)	0.2607475902566641
  :	:
  (319896, 257907)	0.26365675745550726
  (319896, 249587)	0.3328685403347798
  (319896, 220071)	0.19632325749399904
  (319896, 157195)	0.28725645212881734
  (319

In [93]:
# training the machine learning model
model=LogisticRegression(max_iter=1000)

In [94]:
model.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

# Model Evaluation

In [95]:
# accuracy score on the training data
X_train_predicion=model.predict(X_train)
training_data_accuracy=accuracy_score(Y_train,X_train_predicion)

In [96]:
print("Accuracy score on the training data: ", training_data_accuracy)

Accuracy score on the training data:  0.8100959359301784


In [97]:
X_test_predicion=model.predict(X_test)
test_data_accuracy=accuracy_score(Y_test,X_test_predicion)

In [99]:
print("Accuracy score on the training data: ", test_data_accuracy)

Accuracy score on the training data:  0.7787565528085252


In [100]:
# Check number of features in training and test sets
print("Number of features in X_train:", X_train.shape[1])
print("Number of features in X_test:", X_test.shape[1])

# If they are different, reapply preprocessing steps to ensure consistency


Number of features in X_train: 460873
Number of features in X_test: 460873


In [101]:
import pickle

In [111]:


# Save the model and vectorizer using pickle
with open('logistic_regression_model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('logestic_regression_tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

In [113]:
# using the saved model for the future predection
loaded_model=pickle.load(open("logistic_regression_model.pkl","rb"))

In [114]:
X_new=X_test[200]
print(Y_test[200])
prediction =model.predict(X_new)
if (prediction[0]==0):
    print("Negetive Tweet")
else:
    print("Positive Tweet")
print(prediction)

1
Positive Tweet
[1]
